version: "3"
services:
  postgres:
    image: postgres
    hostname: localhost
    environment:
      POSTGRES_DB: db
      POSTGRES_USERNAME: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
  minio:
    image: "bitnami/minio:latest"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
